rules:
  no-ids: 2
  property-sort-order: 0
  class-name-format:
    - 1
    - convention: hyphenatedbem
  quotes: 0
  no-important: 0
  nesting-depth:
    - 2
    -
      max-depth: 4
  no-transition-all: 0
  no-misspelled-properties: 0
